# Generated by Django 5.1.1 on 2024-09-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_listing_alter_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='auctionlisting',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='bids',
            field=models.ManyToManyField(related_name='listings', to='auctions.bid'),
        ),
    ]
